export const Frameworks = [
    { id: 1, name: 'React', price: 9.99, prices: "price1", image: '/ReactCard.svg', classes: "ReactP", Description: "React is a JavaScript library used for building user interfaces. It allows developers to create reusable UI components and efficiently update and render them when the underlying data changes. React follows a component-based architecture and promotes a declarative programming style, making it easier to manage complex UIs and handle state changes.", Descriptions: "Description1", frameworkcard: "framework-card1" },
    { id: 2, name: 'Bootstrap', price: 14.99, prices: "prices2", image: '/BootstrapCard.svg', classes: "BootstrapP", Description: "Bootstrap is a popular front-end framework that simplifies the process of building responsive and mobile-first websites and web applications. It provides a set of pre-designed CSS styles and JavaScript components that can be easily integrated into projects. With Bootstrap, developers can save time and effort by leveraging its grid system, typography, navigation, forms, and other ready-to-use components.", Descriptions: "Description2", frameworkcard: "framework-card2" },
    { id: 3, name: 'Node', price: 19.99, prices: "price3", image: '/Nodecard.svg', classes: "NodeP", Description: "Node.js is a runtime environment built on the Chrome V8 JavaScript engine that allows developers to execute JavaScript code on the server-side. It enables the development of scalable and high-performance web applications by utilizing an event-driven, non-blocking I/O model. Node.js is particularly well-suited for building real-time applications, APIs, microservices, and server-side applications.", Descriptions: "Description3", frameworkcard: "framework-card3" },
    { id: 4, name: 'Express', price: 19.99, prices: "price4", image: '/Expresscard.svg', classes: "ExpressP", Description: "Express is a minimal and flexible web application framework for Node.js. It provides a robust set of features for building web applications and APIs, including routing, middleware support, and template engines. With Express, developers can quickly create server-side applications with ease, handle HTTP requests and responses, and efficiently manage routes and middleware for building scalable and modular web applications.", Descriptions: "Description4", frameworkcard: "framework-card4" },
    { id: 5, name: 'Flask', price: 19.99, prices: "price5", image: '/FlaskCard.svg', classes: "FlaskP", Description: "Flask is a lightweight and flexible web framework for Python that allows developers to build web applications with simplicity and ease. It provides essential tools and libraries for routing, handling HTTP requests and responses, and rendering templates. Flask follows a minimalist approach, enabling developers to choose and integrate additional libraries as needed..", Descriptions: "Description5", frameworkcard: "framework-card5" },
    { id: 6, name: 'Angular', price: 19.99, prices: "price6", image: '/AngularCard.svg', classes: "AngularP", Description: "Angular is a powerful JavaScript framework developed by Google for building dynamic and scalable web applications. It follows the Model-View-Controller (MVC) architectural pattern and provides a comprehensive set of tools and features for front-end development. Angular's two-way data binding, dependency injection, and component-based structure make it efficient for building complex and interactive user interfaces.", Descriptions: "Description6", frameworkcard: "framework-card6" },
    { id: 7, name: 'jQuery', price: 19.99, prices: "price7", image: '/jQueryCard.svg', classes: "jQueryP", Description: "jQuery is a fast and concise JavaScript library that simplifies HTML document traversal, event handling, and animation. It provides a wide range of utilities and functions that make it easier to manipulate and interact with DOM elements. With jQuery, developers can write shorter and more concise code to perform common tasks, such as selecting elements..", Descriptions: "Description7", frameworkcard: "framework-card7" },
    { id: 8, name: 'Vue', price: 19.99, prices: "price8", image: '/VueCard.svg', classes: "VueP", Description: "Vue.js is a progressive JavaScript framework for building user interfaces. It allows developers to create interactive and reactive components that can be easily integrated into existing projects or used to build full-fledged single-page applications. Vue's simplicity, flexibility, and efficient reactivity system make it popular among developers for its ease of use and scalability.", Descriptions: "Description8", frameworkcard: "framework-card8" }
];
  export default Frameworks;