export const products = [
    { id: 1, name: 'JavaScript', price: 9.99, prices: "price1", image: '/JsCard.svg', classes: "JavaScriptP", Description: "JavaScript is a versatile programming language commonly used for web development. It enables interactivity and dynamic behavior on web pages by allowing developers to manipulate the content and behavior of a website. It can be used for tasks ranging from simple form validation to complex web application development.", Descriptions: "Description1", productcard: "product-card1" },
    { id: 2, name: 'Java', price: 14.99, prices: "prices2", image: '/JavaCard.svg', classes: "JavaP", Description: "Java is a widely used object-oriented programming language known for its platform independence. It provides a robust and secure environment for developing applications across various domains, including web, mobile, and enterprise systems. Java's rich ecosystem, including its extensive libraries and products, make it a popular choice for building scalable and high-performance software.", Descriptions: "Description2", productcard: "product-card2" },
    { id: 3, name: 'Python', price: 19.99, prices: "price3", image: '/PythonCard.svg', classes: "PythonP", Description: "Python is a versatile and beginner-friendly programming language known for its simplicity and readability. It offers a wide range of libraries and products that make it suitable for various applications, from web development to data analysis and machine learning. With its clean syntax and extensive documentation, Python has become a popular choice among developers for its efficiency and ease of use.", Descriptions: "Description3", productcard: "product-card3" },
    { id: 4, name: 'HTML', price: 19.99, prices: "price4", image: '/HTMLCard.svg', classes: "HTMLP", Description: " HTML (Hypertext Markup Language) is the standard language used for creating web pages and structuring their content. It uses a series of tags to define the structure, layout, and presentation of a webpage, including headings, paragraphs, images, links, and more. HTML works in conjunction with CSS (Cascading Style Sheets) to style and format the elements on a webpage, creating visually appealing and interactive websites.", Descriptions: "Description4", productcard: "product-card4" },
    { id: 5, name: 'Swift', price: 19.99, prices: "price5", image: '/SwiftCard.svg', classes: "SwiftP", Description: "Swift is a modern, powerful, and intuitive programming language developed by Apple. It is designed to be fast and efficient, enabling developers to write clean and expressive code. With its strong emphasis on safety and performance, Swift has become the preferred language for developing iOS, macOS, watchOS, and tvOS applications.", Descriptions: "Description5", productcard: "product-card5" },
    { id: 6, name: 'Ruby', price: 19.99, prices: "price6", image: '/RubyCard.svg', classes: "RubyP", Description: "Ruby is a dynamic, object-oriented scripting language known for its simplicity and readability. It prioritizes developer happiness by promoting elegant and concise code. Ruby's vast ecosystem of libraries and frameworks, such as Ruby on Rails, makes it a popular choice for web development, enabling rapid prototyping and efficient application building.", Descriptions: "Description6", productcard: "product-card6" },
    { id: 7, name: 'PHP', price: 19.99, prices: "price7", image: '/PHPCard.svg', classes: "PHPP", Description: "PHP is a popular server-side scripting language primarily used for web development. It excels in generating dynamic web content and interacting with databases, making it well-suited for building robust and scalable websites and web applications. PHP offers extensive support for various frameworks and has a large community, providing developers with a wide range of resources and libraries to leverage in their projects.", Descriptions: "Description7", productcard: "product-card7" },
    { id: 8, name: 'C++', price: 19.99, prices: "price8", image: '/CplusCard.svg', classes: "CP", Description: "C++ is a powerful, general-purpose programming language known for its efficiency and performance. It offers a wide range of features, including strong typing, low-level memory manipulation, and object-oriented programming. With its ability to handle both high-level and low-level tasks, C++ is widely used in areas such as game development, system programming, and embedded systems.", Descriptions: "Description8", productcard: "product-card8" }
]; 
export default products;